In [4]:
import pandas as pd
import numpy as np
import os 

os.chdir('D:\OneDrive - National University of Singapore\exchange')

dataset = pd.read_csv (r'D:\OneDrive - National University of Singapore\exchange\ps1.csv')
modlist = pd.read_excel(r'D:\OneDrive - National University of Singapore\exchange\Book1.xlsx')
print(dataset)

                  Faculty                                Partner University  \
0     School of Computing              The Hong Kong Polytechnic University
1     School of Computing              The Hong Kong Polytechnic University
2     School of Computing              The Hong Kong Polytechnic University
3     School of Computing              The Hong Kong Polytechnic University
4     School of Computing              The Hong Kong Polytechnic University
5     School of Computing              The Hong Kong Polytechnic University
6     School of Computing      Hong Kong University of Science & Technology
7     School of Computing      Hong Kong University of Science & Technology
8     School of Computing      Hong Kong University of Science & Technology
9     School of Computing      Hong Kong University of Science & Technology
10    School of Computing      Hong Kong University of Science & Technology
11    School of Computing      Hong Kong University of Science & Technology
12    School of Computing      Hong Kong University of Science & Technology
13    School of Computing      Hong Kong University of Science & Technology
14    School of Computing      Hong Kong University of Science & Technology
15    School of Computing      Hong Kong University of Science & Technology
16    School of Computing      Hong Kong University of Science & Technology
17    School of Computing      Hong Kong University of Science & Technology
18    School of Computing      Hong Kong University of Science & Technology
19    School of Computing      Hong Kong University of Science & Technology
20    School of Computing      Hong Kong University of Science & Technology
21    School of Computing      Hong Kong University of Science & Technology
22    School of Computing      Hong Kong University of Science & Technology
23    School of Computing      Hong Kong University of Science & Technology
24    School of Computing      Hong Kong University of Science & Technology
25    School of Computing      Hong Kong University of Science & Technology
26    School of Computing      Hong Kong University of Science & Technology
27    School of Computing      Hong Kong University of Science & Technology
28    School of Computing      Hong Kong University of Science & Technology
29    School of Computing      Hong Kong University of Science & Technology
...                   ...                                               ...
1850  School of Computing                             Chang Gung University
1851  School of Computing                               Reichman University
1852  School of Computing                               Reichman University
1853  School of Computing                               Reichman University
1854  School of Computing                               Reichman University
1855  School of Computing                               Reichman University
1856  School of Computing                               Reichman University
1857  School of Computing                               Reichman University
1858  School of Computing  Cornell Univ Coll of Agriculture & Life Sciences
1859  School of Computing  Cornell Univ Coll of Agriculture & Life Sciences
1860  School of Computing                Cornell Univ Coll of Human Ecology
1861  School of Computing                          University of Gothenburg
1862  School of Computing                          University of Gothenburg
1863  School of Computing                          University of Gothenburg
1864  School of Computing                          University of Gothenburg
1865  School of Computing                          University of Gothenburg
1866  School of Computing                          University of Gothenburg
1867  School of Computing                          University of Gothenburg
1868  School of Computing                          University of Gothenburg
1869  School of Computing                          University of Gothenburg
1870  School of Computing                          University of Gothenburg
1871  School of Computing                                Western University
1872  School of Computing                                Western University
1873  School of Computing                                Western University
1874  School of Computing                                Western University
1875  School of Computing                                Western University
1876  School of Computing                                Colgate University
1877  School of Computing                 Universitat Autonoma de Barcelona
1878  School of Computing                 Universitat Autonoma de Barcelona
1879  School of Computing                 Universitat Autonoma de Barcelona

         PU Module 1                                  PU Module 1 Title  \
0           COMP3921  FinTech Seminars and Case Studies (I, II and III)
1           COMP4133                              Information Retrieval
2             MM3841                                             MM3841
3             AMA358          Applied probability models for investment
4           COMP3512  Legal Aspects, Professionalism and Ethics of C...
5           COMP3011                  Design and Analysis of Algorithms
6           COMP2611                              Computer Organization
7           ELEC2300                              Computer Organization
8           COMP4461                         Human-Computer Interaction
9           COMP2521            Mobile Application Development Projects
10          COMP4521                     Mobile Application Development
11          COMP3632                        Principles of Cybersecurity
12          COMP5711    Introduction to Advanced Algorithmic Techniques
13          COMP4321         Search Engines for Web and Enterprise Data
14          COMP4111                     Software Engineering Practices
15          COMP5112                               Parallel Programming
16          COMP5311           Database Architecture and Implementation
17          comp5712         Introduction to Combinatorial Optimization
18          ISOM4840            Financial Service Operations Management
19          COMP4911                                IT Entrepreneurship
20          COMP3111                               Software Engineering
21          ISOM3180  Tele communications and Computer Networking Ma...
22          ISOM3010             Information Systems Project Management
23          COMP4641  Social Information Network Analysis and Engine...
24          ISOM4100          Information Systems Auditing and Security
25          COMP3311                        Database Management Systems
26          ISOM3260                 Database Design and Administration
27          COMP4621                  Computer Communication Networks 1
28          COMP2711   Discrete Mathematical Tools for Computer Science
29          ISOM4740                     Enterprise Resource Management
...              ...                                                ...
1850          IM1015               Introduction to Computer Science (I)
1851         IS10342                       Technology and Law (Lecture)
1852           CS644                       Computability and Complexity
1853       201064303                      Automata and Formal Languages
1854       201361501             Blockchain, Consensus and Cryptography
1855       202360001                           Deep Learning (Elective)
1856          CS3141               Machine Learning from Data (Lecture)
1857   3153201315301              Virtual Reality Development(Elective)
1858        INFO1200                Information Ethics, Law, and Policy
1859        INFO4301  Ethics in New Media, Technology, and Communica...
1860          CS2110    Object-Oriented Programming and Data Structures
1861          DIT032                                    Data Management
1862          DIT844                                 Project Management
1863          TIA014     Governance and Control for Digital Capabilitie
1864          TIA014     Governance and Control for Digital Capabilitie
1865          TIG095                         Human-Computer Interaction
1866          DIT405                Introduction to Data Science and AI
1867          DIT602                                         Algorithms
1868          DIT621                                          Databases
1869          DIT401                                  Operating Systems
1870          DIT223                                  Computer Graphics
1871          CS4487                      Algorithms for Image Analysis
1872          CS3319                                        Databases I
1873         CS3346A                          Artificial Intelligence I
1874   COMPSCI402A/B                   DISTRIBUTED AND PARALLEL SYSTEMS
1875  COMPSCI3340A/B                           Analysis of Algorithms I
1876        COSC101A                               Intro to Computing I
1877             NaN                 Leadership, Negotiation Techniques
1878          215887                                  Computer Networks
1879             NaN                               Advanced Programming

      PU Mod1 Credits  PU Module 2  PU Module 2 Title  PU Mod2 Credits  \
0                 3.0          NaN                NaN              NaN
1                 3.0          NaN                NaN              NaN
2                 3.0          NaN                NaN              NaN
3                 3.0          NaN                NaN              NaN
4                 3.0          NaN                NaN              NaN
5                 3.0          NaN                NaN              NaN
6                 4.0          NaN                NaN              NaN
7                 4.0          NaN                NaN              NaN
8                 3.0          NaN                NaN              NaN
9                 3.0          NaN                NaN              NaN
10                3.0          NaN                NaN              NaN
11                3.0          NaN                NaN              NaN
12                3.0          NaN                NaN              NaN
13                3.0          NaN                NaN              NaN
14                3.0          NaN                NaN              NaN
15                3.0          NaN                NaN              NaN
16                3.0          NaN                NaN              NaN
17                3.0          NaN                NaN              NaN
18                3.0          NaN                NaN              NaN
19                3.0          NaN                NaN              NaN
20                4.0          NaN                NaN              NaN
21                3.0          NaN                NaN              NaN
22                3.0          NaN                NaN              NaN
23                3.0          NaN                NaN              NaN
24                3.0          NaN                NaN              NaN
25                3.0          NaN                NaN              NaN
26                3.0          NaN                NaN              NaN
27                3.0          NaN                NaN              NaN
28                4.0          NaN                NaN              NaN
29                3.0          NaN                NaN              NaN
...               ...          ...                ...              ...
1850              3.0          NaN                NaN              NaN
1851              2.0          NaN                NaN              NaN
1852              4.0          NaN                NaN              NaN
1853              4.0          NaN                NaN              NaN
1854              3.0          NaN                NaN              NaN
1855              3.0          NaN                NaN              NaN
1856              4.0          NaN                NaN              NaN
1857              3.0          NaN                NaN              NaN
1858              3.0          NaN                NaN              NaN
1859              3.0          NaN                NaN              NaN
1860              3.0          NaN                NaN              NaN
1861              7.5          NaN                NaN              NaN
1862              7.5          NaN                NaN              NaN
1863              7.5          NaN                NaN              NaN
1864              7.5          NaN                NaN              NaN
1865              7.5          NaN                NaN              NaN
1866              7.5          NaN                NaN              NaN
1867              7.5          NaN                NaN              NaN
1868              7.5          NaN                NaN              NaN
1869              7.5          NaN                NaN              NaN
1870              7.5          NaN                NaN              NaN
1871              4.0          NaN                NaN              NaN
1872              4.0          NaN                NaN              NaN
1873              4.0          NaN                NaN              NaN
1874              4.0          NaN                NaN              NaN
1875              4.0          NaN                NaN              NaN
1876              1.0          NaN                NaN              NaN
1877              6.0          NaN                NaN              NaN
1878              6.0          NaN                NaN              NaN
1879              6.0          NaN                NaN              NaN

     NUS Module 1              NUS Module 1 Title  NUS Mod1 Credits  \
0          IS4228  Information Technologies in Fi               4.0
1          BT4222  Mining Web Data for Business I               4.0
2          IS3240   Digital Platform Strategy and               4.0
3          BT4013  Analytics for Capital Market T               4.0
4          IS1103             Ethics in Computing               4.0
5          CS3230  Design & Analysis of Algorithm               4.0
6          CS2100           Computer Organisation               4.0
7          CS2100           Computer Organisation               4.0
8          CS3240              Interaction Design               4.0
9          IS3261  Mobile Apps Development for En               4.0
10         IS3261  Mobile Apps Development for En               4.0
11         CS2107  Introduction to Information Se               4.0
12         CS3230  Design & Analysis of Algorithm               4.0
13         CS3245           Information Retrieval               4.0
14         CS3219  Software Engineering Principle               4.0
15         CS3210              Parallel Computing               4.0
16         CS3223  Database Systems Implementatio               4.0
17         CS4234         Optimisation Algorithms               4.0
18         IS4228  Information Technologies in Fi               4.0
19         CS4880        Digital Entrepreneurship               4.0
20         CS2103            Software Engineering               4.0
21         CS2105      Intro to Computer Networks               4.0
22         IS4100           IT Project Management               4.0
23         IS4241   Social Media Network Analysis               4.0
24         IS4234  Compliance and Regulation Tech               4.0
25         CS2102                Database Systems               4.0
26         CS2102                Database Systems               4.0
27         CS2105      Intro to Computer Networks               4.0
28         CS1231             Discrete Structures               4.0
29         IS3221  ERP Systems with Analytics Sol               4.0
...           ...                             ...               ...
1850      CS1010S         Programming Methodology               4.0
1851       IS1103             Ethics in Computing               4.0
1852       CS4232                             NaN               4.0
1853       CS4232                             NaN               4.0
1854       IS4302  Blockchain and Distributed Led               4.0
1855       CS5242  Neural Networks &Deep Learning               4.0
1856       CS3244                Machine Learning               4.0
1857       CS4240  Interaction Design for Virtual               4.0
1858       IS1103             Ethics in Computing               4.0
1859       IS1103             Ethics in Computing               4.0
1860       CS2040  Data Structures and Algorithms               4.0
1861       CS2102                Database Systems               4.0
1862       IS4100           IT Project Management               4.0
1863       IS4234  Compliance and Regulation Tech               4.0
1864       IS4204                   IT Governance               4.0
1865       CS3240              Interaction Design               4.0
1866       CS3243  Introduction to Artificial Int               4.0
1867       CS3230  Design & Analysis of Algorithm               4.0
1868       CS2102                Database Systems               4.0
1869       CS2106      Intro to Operating Systems               4.0
1870       CS4247   Graphics Rendering Techniques               4.0
1871       CS4243  Comp Vision & Pattern Recogntn               4.0
1872       CS2102                Database Systems               4.0
1873       CS3243  Introduction to Artificial Int               4.0
1874       CS3210              Parallel Computing               4.0
1875       CS3230  Design & Analysis of Algorithm               4.0
1876      CS1010S         Programming Methodology               4.0
1877       IS3103  Information Systems Leadership               4.0
1878       CS2105      Intro to Computer Networks               4.0
1879       CS2030      Programming Methodology II               4.0

      NUS Module 2  NUS Module 2 Title  NUS Mod2 Credits Pre Approved?  \
0              NaN                 NaN               NaN             N
1              NaN                 NaN               NaN             N
2              NaN                 NaN               NaN             N
3              NaN                 NaN               NaN             N
4              NaN                 NaN               NaN             Y
5              NaN                 NaN               NaN             N
6              NaN                 NaN               NaN           NaN
7              NaN                 NaN               NaN           NaN
8              NaN                 NaN               NaN           NaN
9              NaN                 NaN               NaN           NaN
10             NaN                 NaN               NaN             N
11             NaN                 NaN               NaN           NaN
12             NaN                 NaN               NaN             N
13             NaN                 NaN               NaN             N
14             NaN                 NaN               NaN             N
15             NaN                 NaN               NaN             N
16             NaN                 NaN               NaN             N
17             NaN                 NaN               NaN             N
18             NaN                 NaN               NaN           NaN
19             NaN                 NaN               NaN           NaN
20             NaN                 NaN               NaN           NaN
21             NaN                 NaN               NaN           NaN
22             NaN                 NaN               NaN           NaN
23             NaN                 NaN               NaN           NaN
24             NaN                 NaN               NaN           NaN
25             NaN                 NaN               NaN           NaN
26             NaN                 NaN               NaN           NaN
27             NaN                 NaN               NaN           NaN
28             NaN                 NaN               NaN             Y

In [6]:
df = dataset.loc[(dataset['NUS Module 1'].isin(modlist['MODS']))]
print(df)
df.to_csv('df_result.csv', header = True)

                  Faculty                             Partner University  \
0     School of Computing           The Hong Kong Polytechnic University
1     School of Computing           The Hong Kong Polytechnic University
3     School of Computing           The Hong Kong Polytechnic University
9     School of Computing   Hong Kong University of Science & Technology
10    School of Computing   Hong Kong University of Science & Technology
18    School of Computing   Hong Kong University of Science & Technology
23    School of Computing   Hong Kong University of Science & Technology
24    School of Computing   Hong Kong University of Science & Technology
29    School of Computing   Hong Kong University of Science & Technology
36    School of Computing                   City University of Hong Kong
37    School of Computing                   City University of Hong Kong
38    School of Computing                   City University of Hong Kong
44    School of Computing                   City University of Hong Kong
49    School of Computing                   City University of Hong Kong
52    School of Computing                   City University of Hong Kong
54    School of Computing                   City University of Hong Kong
55    School of Computing                   City University of Hong Kong
56    School of Computing                   City University of Hong Kong
60    School of Computing                   City University of Hong Kong
61    School of Computing                    The University of Hong Kong
70    School of Computing                    The University of Hong Kong
74    School of Computing                    The University of Hong Kong
78    School of Computing                    The University of Hong Kong
80    School of Computing                    The University of Hong Kong
81    School of Computing                    The University of Hong Kong
82    School of Computing                    The University of Hong Kong
94    School of Computing            The Chinese University of Hong Kong
95    School of Computing            The Chinese University of Hong Kong
102   School of Computing            The Chinese University of Hong Kong
114   School of Computing               University College Cork, Ireland
...                   ...                                            ...
1680  School of Computing            University of California, San Diego
1684  School of Computing           University of California, Santa Cruz
1690  School of Computing        University of California, Santa Barbara
1691  School of Computing        University of California, Santa Barbara
1693  School of Computing               University of California, Irvine
1697  School of Computing               University of California, Irvine
1705  School of Computing                University of California, Davis
1706  School of Computing                University of California, Davis
1716  School of Computing                University of California, Davis
1717  School of Computing                University of California, Davis
1723  School of Computing                              Boston University
1724  School of Computing                              Boston University
1731  School of Computing                              Boston University
1735  School of Computing                              Boston University
1736  School of Computing                              Boston University
1752  School of Computing                              Boston University
1758  School of Computing                       Arizona State University
1759  School of Computing                       Arizona State University
1774  School of Computing                       Arizona State University
1787  School of Computing      Pohang University of Science & Technology
1788  School of Computing      Pohang University of Science & Technology
1814  School of Computing                             Bilkent University
1817  School of Computing                             Bilkent University
1818  School of Computing                             Bilkent University
1821  School of Computing               University of California, Merced
1837  School of Computing                       University of St Andrews
1843  School of Computing  Singapore University of Technology and Design
1854  School of Computing                            Reichman University
1856  School of Computing                            Reichman University
1863  School of Computing                       University of Gothenburg

     PU Module 1                                  PU Module 1 Title  \
0       COMP3921  FinTech Seminars and Case Studies (I, II and III)
1       COMP4133                              Information Retrieval
3         AMA358          Applied probability models for investment
9       COMP2521            Mobile Application Development Projects
10      COMP4521                     Mobile Application Development
18      ISOM4840            Financial Service Operations Management
23      COMP4641  Social Information Network Analysis and Engine...
24      ISOM4100          Information Systems Auditing and Security
29      ISOM4740                     Enterprise Resource Management
36        MS4111                       Enterprise Resource Planning
37        CS4295                     Mobile Application Programming
38        IS4837            Delivery Systems for Financial Services
44        IS4835      Information Technology for Financial Services
49        IS4340                         Search Engine Optimization
52        MS4226                             Risk Management Models
54       MKT4636                             Data-centric Marketing
55        CS4480                           Data-Intensive Computing
56        CS5488                 Big Data Algorithms and Techniques
60        IS4537                          Information Systems Audit
61     IIMT3686A              Information Systems Audit and Control
70      COMP3314                                   Machine Learning
74      IIMT3686              Information Systems Audit and Control
78      STAT3618                    Derivatives and risk management
80      STAT3609                  The statistics of investment risk
81      STAT3613                              Marketing engineering
82      STAT4607                               Credit risk analysis
94     CSCI 3310      Mobile Computing and Applications Development
95     CSCI 5590                      Advanced Topics in Blockchain
102     CSCI4190                    Introduction to Social Networks
114       MF2053        Financial Modelling for Actuarial Science 1
...          ...                                                ...
1680     CSE151A                   Introduction to Machine Learning
1684      CSE148                                   Machine Learning
1690   PSTAT 173                                        Risk Theory
1691     COMP169                                     Social Network
1693     BANA227                           Web and Social Analytics
1697   COMPSC178                   Machine Learning and Data-Mining
1705      CSE151  Introduction to Artificial Intelligence: Stati...
1706    STAT141B          Data & Web Technologies for Data Analysis
1716      ECS171                                   Machine Learning
1717    COGS118A                        Intro to Machine Learning I
1723   MET AD654                                MARKETING ANALYTICS
1724       AD571                     Business Analytics Foundations
1731   MET CS688                           Web Analytics and Mining
1735  MET AD 685                   Quantitative Methods for Finance
1736  MET AD 717       Investment Analysis and Portfolio Management
1752  ENG EC 414                   Introduction to Machine Learning
1758      SER421          Web-Based Applications and Mobile Systems
1759      CSE494                   Introduction to Machine Learning
1774      CSE535                                   Mobile Computing
1787     CSED515                                   Machine Learning
1788    CSED490B                ST:Introduction to Machine Learning
1814       CS550                                   Machine Learning
1817     CTIS464                   Introduction to Machine Learning
1818     CTIS487                     Mobile Application Development
1821      CSE176                   Introduction to Machine Learning
1837      CS5014                                   Machine Learning
1843      50.007                                   Machine Learning
1854   201361501             Blockchain, Consensus and Cryptography
1856      CS3141               Machine Learning from Data (Lecture)
1863      TIA014     Governance and Control for Digital Capabilitie

      PU Mod1 Credits  PU Module 2  PU Module 2 Title  PU Mod2 Credits  \
0                 3.0          NaN                NaN              NaN
1                 3.0          NaN                NaN              NaN
3                 3.0          NaN                NaN              NaN
9                 3.0          NaN                NaN              NaN
10                3.0          NaN                NaN              NaN
18                3.0          NaN                NaN              NaN
23                3.0          NaN                NaN              NaN
24                3.0          NaN                NaN              NaN
29                3.0          NaN                NaN              NaN
36                3.0          NaN                NaN              NaN
37                3.0          NaN                NaN              NaN
38                3.0          NaN                NaN              NaN
44                3.0          NaN                NaN              NaN
49                3.0          NaN                NaN              NaN
52                3.0          NaN                NaN              NaN
54                3.0          NaN                NaN              NaN
55                3.0          NaN                NaN              NaN
56                3.0          NaN                NaN              NaN
60                3.0          NaN                NaN              NaN
61                6.0          NaN                NaN              NaN
70                6.0          NaN                NaN              NaN
74                6.0          NaN                NaN              NaN
78                6.0          NaN                NaN              NaN
80                6.0          NaN                NaN              NaN
81                6.0          NaN                NaN              NaN
82                6.0          NaN                NaN              NaN
94                3.0          NaN                NaN              NaN
95                3.0          NaN                NaN              NaN
102               3.0          NaN                NaN              NaN
114               5.0          NaN                NaN              NaN
...               ...          ...                ...              ...
1680              3.0          NaN                NaN              NaN
1684              5.0          NaN                NaN              NaN
1690              3.0          NaN                NaN              NaN
1691              3.0          NaN                NaN              NaN
1693              3.0          NaN                NaN              NaN
1697              3.0          NaN                NaN              NaN
1705              3.0          NaN                NaN              NaN
1706              3.0          NaN                NaN              NaN
1716              3.0          NaN                NaN              NaN
1717              3.0          NaN                NaN              NaN
1723              4.0          NaN                NaN              NaN
1724              4.0          NaN                NaN              NaN
1731              4.0          NaN                NaN              NaN
1735              4.0          NaN                NaN              NaN
1736              4.0          NaN                NaN              NaN
1752              3.0          NaN                NaN              NaN
1758              3.0          NaN                NaN              NaN
1759              3.0          NaN                NaN              NaN
1774              3.0          NaN                NaN              NaN
1787              3.0          NaN                NaN              NaN
1788              3.0          NaN                NaN              NaN
1814              3.0          NaN                NaN              NaN
1817              3.0          NaN                NaN              NaN
1818              3.0          NaN                NaN              NaN
1821              4.0          NaN                NaN              NaN
1837             15.0          NaN                NaN              NaN
1843             12.0          NaN                NaN              NaN
1854              3.0          NaN                NaN              NaN
1856              4.0          NaN                NaN              NaN
1863              7.5          NaN                NaN              NaN

     NUS Module 1              NUS Module 1 Title  NUS Mod1 Credits  \
0          IS4228  Information Technologies in Fi               4.0
1          BT4222  Mining Web Data for Business I               4.0
3          BT4013  Analytics for Capital Market T               4.0
9          IS3261  Mobile Apps Development for En               4.0
10         IS3261  Mobile Apps Development for En               4.0
18         IS4228  Information Technologies in Fi               4.0
23         IS4241   Social Media Network Analysis               4.0
24         IS4234  Compliance and Regulation Tech               4.0
29         IS3221  ERP Systems with Analytics Sol               4.0
36         IS3221  ERP Systems with Analytics Sol               4.0
37         IS3261  Mobile Apps Development for En               4.0
38         IS4228  Information Technologies in Fi               4.0
44         IS4228  Information Technologies in Fi               4.0
49         BT4212  Search Engine Optimization & A               4.0
52         BT4016  Risk Analytics for Financial S               4.0
54         BT4211           Data-Driven Marketing               4.0
55         BT4211           Data-Driven Marketing               4.0
56         BT4211           Data-Driven Marketing               4.0
60         IS4234  Compliance and Regulation Tech               4.0
61         IS4234  Compliance and Regulation Tech               4.0
70         CS3244                Machine Learning               4.0
74         IS4234  Compliance and Regulation Tech               4.0
78         BT4016  Risk Analytics for Financial S               4.0
80         BT4016  Risk Analytics for Financial S               4.0
81         BT4211           Data-Driven Marketing               4.0
82         BT4016  Risk Analytics for Financial S               4.0
94         IS3261  Mobile Apps Development for En               4.0
95         IS4302  Blockchain and Distributed Led               4.0
102        IS4241   Social Media Network Analysis               4.0
114        BT4016  Risk Analytics for Financial S               4.0
...           ...                             ...               ...
1680       CS3244                Machine Learning               4.0
1684       CS3244                Machine Learning               4.0
1690       BT4016  Risk Analytics for Financial S               4.0
1691       IS4241   Social Media Network Analysis               4.0
1693       IS4241   Social Media Network Analysis               4.0
1697       CS3244                Machine Learning               4.0
1705       CS3244                Machine Learning               4.0
1706       BT4222  Mining Web Data for Business I               4.0
1716       CS3244                Machine Learning               4.0
1717       CS3244                Machine Learning               4.0
1723       BT4211           Data-Driven Marketing               4.0
1724       BT4240  Machine Learning for Predictiv               4.0
1731       BT4222  Mining Web Data for Business I               4.0
1735       BT4013  Analytics for Capital Market T               4.0
1736       BT4013  Analytics for Capital Market T               4.0
1752       CS3244                Machine Learning               4.0
1758       IS3261  Mobile Apps Development for En               4.0
1759       CS3244                Machine Learning               4.0
1774       IS3261  Mobile Apps Development for En               4.0
1787       CS3244                Machine Learning               4.0
1788       CS3244                Machine Learning               4.0
1814       CS3244                Machine Learning               4.0
1817       CS3244                Machine Learning               4.0
1818       IS3261  Mobile Apps Development for En               4.0
1821       CS3244                Machine Learning               4.0
1837       CS3244                Machine Learning               4.0
1843       CS3244                Machine Learning               4.0
1854       IS4302  Blockchain and Distributed Led               4.0
1856       CS3244                Machine Learning               4.0
1863       IS4234  Compliance and Regulation Tech               4.0

      NUS Module 2  NUS Module 2 Title  NUS Mod2 Credits Pre Approved?  \
0              NaN                 NaN               NaN             N
1              NaN                 NaN               NaN             N
3              NaN                 NaN               NaN             N
9              NaN                 NaN               NaN           NaN
10             NaN                 NaN               NaN             N
18             NaN                 NaN               NaN           NaN
23             NaN                 NaN               NaN           NaN
24             NaN                 NaN               NaN           NaN
29             NaN                 NaN               NaN           NaN
36             NaN                 NaN               NaN           NaN
37             NaN                 NaN               NaN           NaN
38             NaN                 NaN               NaN           NaN
44             NaN                 NaN               NaN           NaN
49             NaN                 NaN               NaN             N
52             NaN                 NaN               NaN             N
54             NaN                 NaN               NaN           NaN
55             NaN                 NaN               NaN           NaN
56             NaN                 NaN               NaN           NaN
60             NaN                 NaN               NaN           NaN
61             NaN                 NaN               NaN           NaN
70             NaN                 NaN               NaN             N
74             NaN                 NaN               NaN             N
78             NaN                 NaN               NaN             N
80             NaN                 NaN               NaN             N
81             NaN                 NaN               NaN             N
82             NaN                 NaN               NaN             N
94             NaN                 NaN               NaN             N
95             NaN                 NaN               NaN             N
102            NaN                 NaN               NaN           NaN
114            NaN                 NaN               NaN           NaN
...            ...                 ...               ...           ...
1680           NaN                 NaN               NaN           NaN
1684           NaN                 NaN               NaN           NaN
1690           NaN                 NaN               NaN             N
1691           NaN                 NaN               NaN             N